[package]
name = "zino-ntex"
description = "Integrations with ntex for zino."
version = "0.6.1"
rust-version = "1.80"
edition = "2021"
license = "MIT"
categories = ["asynchronous", "network-programming", "web-programming"]
keywords = ["http", "web", "framework"]
homepage = "https://github.com/zino-rs/zino"
repository = "https://github.com/zino-rs/zino"
documentation = "https://docs.rs/zino-ntex"
readme = "README.md"

[features]
orm = ["zino-orm", "zino-orm/openapi"]

[dependencies]
ntex-files = "2.0.0"
futures = { workspace = true }
tracing = { workspace = true }
zino-core = { workspace = true, features = ["runtime-tokio"] }
zino-http = { workspace = true }
zino-orm = { workspace = true, optional = true }

[dependencies.ntex]
version = "2.11.0"
default-features = false
features = ["compress", "tokio"]

[lints]
workspace = true
