[package]
name = "zino-ntex"
description = "Integrations with ntex for zino."
version = "0.7.0"
categories = ["asynchronous", "network-programming", "web-programming"]
keywords = ["http", "web", "framework"]
readme = "README.md"
documentation = "https://docs.rs/zino-ntex"
homepage = { workspace = true }
repository = { workspace = true }
edition = { workspace = true }
rust-version = { workspace = true }
license = { workspace = true }

[features]
orm = ["zino-orm", "zino-orm/openapi"]

[dependencies]
ntex-files = "2.0.0"
futures = { workspace = true }
tracing = { workspace = true }
zino-core = { workspace = true, features = ["runtime-tokio"] }
zino-http = { workspace = true }
zino-orm = { workspace = true, optional = true }

[dependencies.ntex]
version = "2.12.2"
default-features = false
features = ["compress", "tokio"]

[lints]
workspace = true
