[package]
name = "zino-openapi"
description = "OpenAPI support for zino."
version = "0.1.0"
rust-version = "1.80"
edition = "2021"
license = "MIT"
categories = ["asynchronous", "network-programming", "web-programming"]
keywords = ["http", "web", "framework"]
homepage = "https://github.com/zino-rs/zino"
repository = "https://github.com/zino-rs/zino"
documentation = "https://docs.rs/zino-openapi"
readme = "README.md"

[features]
debug = [
    "utoipa/preserve_order",
    "utoipa/preserve_path_order",
    "zino-core/debug",
]

[dependencies]
ahash = "0.8.11"
convert_case = "0.6.0"
serde_json = "1.0.134"
tracing = "0.1.41"

[dependencies.toml]
version = "0.8.19"
default-features = false

[dependencies.utoipa]
version = "5.3.0"
features = [
    "non_strict_integers",
    "url",
    "ulid",
    "uuid",
]

[dependencies.zino-core]
path = "../zino-core"
version = "0.30.0"
