[package]
name = "zino-openapi"
description = "OpenAPI support for zino."
version = "0.3.0"
rust-version = "1.80"
edition = "2021"
license = "MIT"
categories = ["asynchronous", "network-programming", "web-programming"]
keywords = ["http", "web", "framework"]
homepage = "https://github.com/zino-rs/zino"
repository = "https://github.com/zino-rs/zino"
documentation = "https://docs.rs/zino-openapi"
readme = "README.md"

[features]
debug = [
    "utoipa/preserve_order",
    "utoipa/preserve_path_order",
    "zino-core/debug",
]

[dependencies]
ahash = { workspace = true }
convert_case = { workspace = true }
serde_json = { workspace = true }
toml = { workspace = true }
tracing = { workspace = true }
zino-core = { workspace = true }

[dependencies.utoipa]
version = "5.3.1"
features = [
    "non_strict_integers",
    "ulid",
    "url",
    "uuid",
]

[lints]
workspace = true
