[package]
name = "zino-extra"
description = "Extra utilities for zino."
version = "0.9.1"
categories = ["asynchronous", "network-programming", "web-programming"]
keywords = ["http", "web", "framework"]
readme = "README.md"
documentation = "https://docs.rs/zino-extra"
homepage = { workspace = true }
repository = { workspace = true }
edition = { workspace = true }
rust-version = { workspace = true }
license = { workspace = true }

[package.metadata.docs.rs]
features = ["full"]
cargo-args = ["-Zunstable-options", "-Zrustdoc-scrape-examples"]
rustdoc-args = ["--cfg", "docsrs"]

[features]
all-formats = ["format", "format-pdf"]
cache = ["dep:lru", "dep:parking_lot"]
default = []
format = []
format-pdf = ["format", "dep:printpdf"]
full = ["all-formats", "cache"]

[dependencies]
parking_lot = { workspace = true, optional = true }
zino-core = { workspace = true }

[dependencies.lru]
version = "0.13.0"
optional = true

[dependencies.printpdf]
version = "0.8.2"
optional = true

[lints]
workspace = true
