[package]
name = "zino-extra"
description = "Extra utilities for zino."
version = "0.8.0"
rust-version = "1.80"
edition = "2021"
license = "MIT"
categories = ["asynchronous", "network-programming", "web-programming"]
keywords = ["http", "web", "framework"]
homepage = "https://github.com/zino-rs/zino"
repository = "https://github.com/zino-rs/zino"
documentation = "https://docs.rs/zino-extra"
readme = "README.md"

[package.metadata.docs.rs]
features = ["full"]
cargo-args = ["-Zunstable-options", "-Zrustdoc-scrape-examples"]
rustdoc-args = ["--cfg", "docsrs"]

[features]
all-formats = ["format", "format-pdf"]
cache = ["dep:lru", "dep:parking_lot"]
default = []
format = []
format-pdf = ["format", "dep:printpdf"]
full = ["all-formats", "cache"]

[dependencies]
parking_lot = { workspace = true, optional = true }
zino-core = { workspace = true }

[dependencies.lru]
version = "0.13.0"
optional = true

[dependencies.printpdf]
version = "0.7.0"
optional = true

[lints]
workspace = true
