[package]
name = "zino-rpc"
description = "RPC support for zino."
version = "0.0.1"
categories = ["asynchronous", "network-programming", "web-programming"]
keywords = ["http", "web", "framework"]
homepage = { workspace = true }
repository = { workspace = true }
readme = { workspace = true }
edition = { workspace = true }
rust-version = { workspace = true }
license = { workspace = true }

[dependencies]

[lints]
workspace = true
