[package]
name = "zino"
description = "Next-generation framework for composable applications in Rust."
version = "0.28.2"
rust-version = "1.80"
edition = "2021"
license = "MIT"
categories = ["asynchronous", "network-programming", "web-programming::http-server"]
keywords = ["http", "web", "framework"]
homepage = "https://github.com/zino-rs/zino"
repository = "https://github.com/zino-rs/zino"
documentation = "https://docs.rs/zino"
readme = "README.md"

[package.metadata.docs.rs]
features = [
    "auth",
    "axum",
    "i18n",
    "jwt",
    "oidc",
    "opa",
    "orm",
]
cargo-args = ["-Zunstable-options", "-Zrustdoc-scrape-examples"]
rustdoc-args = ["--cfg", "docsrs"]

[features]
actix = ["dep:zino-actix", "dep:zino-http"]
auth = ["zino-auth", "zino-http?/auth"]
axum = ["dep:zino-axum", "dep:zino-http"]
cookie = ["zino-core/cookie", "zino-http?/cookie"]
dioxus = ["zino-dioxus"]
dioxus-desktop = ["dioxus", "zino-dioxus/desktop"]
debug = ["zino-core/debug"]
default = ["logger"]
i18n = ["dep:zino-http", "zino-http/i18n"]
jwt = ["auth", "zino-auth/jwt", "zino-http?/jwt"]
logger = ["zino-core/tracing-log", "zino-core/tracing-subscriber"]
metrics = ["zino-core/metrics", "zino-http?/metrics", "zino-storage/metrics"]
ntex = ["dep:zino-http", "dep:zino-ntex"]
oidc = ["auth", "zino-core/oidc"]
opa = ["auth", "zino-auth/opa"]
orm = ["zino-axum?/orm", "zino-core/orm"]
view = ["zino-core/view", "zino-http?/view"]

[dependencies]
cfg-if = "1.0"
serde_json = "1.0.133"

[dependencies.zino-actix]
path = "../zino-actix"
version = "0.2.2"
optional = true

[dependencies.zino-auth]
path = "../zino-auth"
version = "0.1.3"
optional = true

[dependencies.zino-axum]
path = "../zino-axum"
version = "0.2.2"
optional = true

[dependencies.zino-core]
path = "../zino-core"
version = "0.29.3"

[dependencies.zino-dioxus]
path = "../zino-dioxus"
version = "0.10.3"
optional = true

[dependencies.zino-storage]
path = "../zino-storage"
version = "0.1.0"

[dependencies.zino-http]
path = "../zino-http"
version = "0.1.3"
optional = true

[dependencies.zino-ntex]
path = "../zino-ntex"
version = "0.2.2"
optional = true
