[package]
name = "dioxus-desktop"
description = "An example for Dioxus desktop integration."
version = "0.10.1"
rust-version = "1.80"
edition = "2021"
publish = false

[dependencies]
dioxus = "0.6.3"
dioxus-router = "0.6.3"
tracing = "0.1.41"

[dependencies.dioxus-free-icons]
version = "0.9.0"
features = [
    "bootstrap",
    "font-awesome-brands",
    "font-awesome-solid",
    "octicons",
]

[dependencies.zino]
path = "../../crates/zino"
version = "0.32.1"
features = ["dioxus-desktop"]

[dependencies.zino-core]
path = "../../crates/zino-core"
version = "0.32.1"
features = ["env-filter", "http-client", "tls-native"]

[dependencies.zino-dioxus]
path = "../../crates/zino-dioxus"
version = "0.13.1"
