[package]
name = "ntex-app"
description = "An example for ntex integration."
version = "0.3.0"
rust-version = "1.80"
edition = "2021"
publish = false

[dependencies]
tracing = "0.1.41"

[dependencies.ntex]
version = "2.8.0"
default-features = false

[dependencies.serde]
version = "1.0.215"
features = ["derive"]

[dependencies.zino]
path = "../../zino"
version = "0.26.3"
features = [
    "i18n",
    "jwt",
    "ntex",
    "orm",
]

[dependencies.zino-core]
path = "../../zino-core"
version = "0.27.3"
features = [
    "cookie",
    "env-filter",
    "orm-postgres",
    "view-minijinja",
]

[dependencies.zino-derive]
path = "../../zino-derive"
version = "0.24.3"

[dependencies.zino-model]
path = "../../zino-model"
version = "0.24.3"
