[package]
name = "zino-orm"
description = "ORM for zino."
version = "0.1.0"
rust-version = "1.80"
edition = "2021"
license = "MIT"
categories = ["asynchronous", "network-programming", "web-programming"]
keywords = ["http", "web", "framework"]
homepage = "https://github.com/zino-rs/zino"
repository = "https://github.com/zino-rs/zino"
documentation = "https://docs.rs/zino-orm"
readme = "README.md"

[features]
default = ["orm-sqlx"]
orm = ["orm-sqlx"]
orm-mariadb = ["orm-sqlx", "sqlx/mysql"]
orm-mysql = ["orm-sqlx", "sqlx/mysql"]
orm-postgres = ["orm-sqlx", "sqlx/postgres"]
orm-sqlite = ["orm-sqlx", "sqlx/sqlite"]
orm-sqlx = ["sqlx", "sqlx/sqlite", "zino-core/sqlx"]
orm-tidb = ["orm-sqlx", "sqlx/mysql"]

[dependencies]
apache-avro = "0.17.0"
cfg-if = "1.0"
chrono = "0.4.39"
convert_case = "0.6.0"
http = "1.2.0"
futures = "0.3.31"
regex = "1.11.1"
serde_json = "1.0.133"
smallvec = "1.13.2"
tracing = "0.1.41"
url = "2.5.4"

[dependencies.serde]
version = "1.0.216"
features = ["derive"]

[dependencies.sqlx]
version = "0.8.2"
optional = true
default-features = false
features = [
    "chrono",
    "json",
    "rust_decimal",
    "uuid",
]

[dependencies.toml]
version = "0.8.19"
default-features = false

[dependencies.zino-core]
path = "../zino-core"
version = "0.29.3"
