[package]
name = "zino-dioxus"
description = "Dioxus components for zino."
version = "0.13.2"
rust-version = "1.80"
edition = "2021"
license = "MIT"
categories = ["gui", "network-programming", "web-programming"]
keywords = ["zino", "dioxus", "components"]
homepage = "https://github.com/zino-rs/zino"
repository = "https://github.com/zino-rs/zino"
documentation = "https://docs.rs/zino-dioxus"
readme = "README.md"

[package.metadata.docs.rs]
features = ["clipboard", "markdown"]
cargo-args = ["-Zunstable-options", "-Zrustdoc-scrape-examples"]
rustdoc-args = ["--cfg", "docsrs"]

[features]
default = []
desktop = ["dep:rust-ini", "dioxus/desktop"]
clipboard = ["dioxus-sdk/clipboard"]
markdown = ["dep:comrak"]

[dependencies]
dioxus = "0.6.3"
dioxus-core = "0.6.3"
dioxus-hooks = "0.6.2"
dioxus-html = "0.6.3"
dioxus-router = "0.6.3"
chrono = { workspace = true }
rust_decimal = { workspace = true }
smallvec = { workspace = true }
tokio = { workspace = true }
tracing = { workspace = true }
uuid = { workspace = true }
zino-core = { workspace = true, features = ["runtime-tokio"] }
zino-storage = { workspace = true }

[dependencies.comrak]
version = "0.35.0"
optional = true
default-features = false
features = ["shortcodes", "syntect"]

[dependencies.dioxus-free-icons]
version = "0.9.0"
features = ["bootstrap", "font-awesome-solid"]

[dependencies.dioxus-sdk]
version = "0.6.0"
optional = true

[dependencies.image]
version = "0.25.5"
default-features = false
features = [
    "gif",
    "ico",
    "jpeg",
    "png",
    "rayon",
]

[dependencies.rust-ini]
version = "0.21.1"
optional = true

[lints]
workspace = true
