[package]
name = "axum-app"
description = "An example for axum integration."
version = "0.16.0"
rust-version = "1.80"
edition = "2021"
publish = false

[dependencies]
tracing = "0.1.41"

[dependencies.axum]
version = "0.7.9"
default-features = false

[dependencies.serde]
version = "1.0.216"
features = ["derive"]

[dependencies.zino]
path = "../../crates/zino"
version = "0.28.2"
features = [
    "axum",
    "cookie",
    "i18n",
    "jwt",
    "orm",
    "view",
]

[dependencies.zino-core]
path = "../../crates/zino-core"
version = "0.29.3"
features = [
    "env-filter",
    "orm-mysql",
    "validator-email",
    "view-tera",
]

[dependencies.zino-derive]
path = "../../crates/zino-derive"
version = "0.26.2"

[dependencies.zino-model]
path = "../../crates/zino-model"
version = "0.26.2"
