[package]
name = "axum-app"
description = "An example for axum integration."
version = "0.19.2"
rust-version = "1.80"
edition = "2021"
publish = false

[dependencies]
tracing = "0.1.41"

[dependencies.axum]
version = "0.8.1"
default-features = false

[dependencies.serde]
version = "1.0.217"
features = ["derive"]

[dependencies.zino]
path = "../../crates/zino"
version = "0.31.3"
features = [
    "axum",
    "cookie",
    "i18n",
    "jwt",
    "orm",
    "view",
]

[dependencies.zino-core]
path = "../../crates/zino-core"
version = "0.31.3"
features = ["env-filter", "validator-email"]

[dependencies.zino-derive]
path = "../../crates/zino-derive"
version = "0.29.2"

[dependencies.zino-model]
path = "../../crates/zino-model"
version = "0.29.2"

[dependencies.zino-orm]
path = "../../crates/zino-orm"
version = "0.3.2"
features = ["orm-mysql"]
