[package]
name = "minimal-app"
description = "A minimal example to run a server."
version = "0.8.1"
rust-version = "1.80"
edition = "2021"
publish = false

[dependencies.zino]
path = "../../crates/zino"
version = "0.31.2"
features = ["axum"]

