[package]
name = "zino-storage"
description = "Files and storage services for zino."
version = "0.8.0"
categories = ["asynchronous", "network-programming", "web-programming"]
keywords = ["http", "web", "framework"]
readme = "README.md"
documentation = "https://docs.rs/zino-storage"
homepage = { workspace = true }
repository = { workspace = true }
edition = { workspace = true }
rust-version = { workspace = true }
license = { workspace = true }

[package.metadata.docs.rs]
features = [
    "all-accessors",
    "http-client",
    "metrics",
]
cargo-args = ["-Zunstable-options", "-Zrustdoc-scrape-examples"]
rustdoc-args = ["--cfg", "docsrs"]

[features]
accessor = ["opendal"]
accessor-azblob = ["accessor", "opendal/services-azblob"]
accessor-azdls = ["accessor", "opendal/services-azdls"]
accessor-cacache = ["accessor", "opendal/services-cacache"]
accessor-cos = ["accessor", "opendal/services-cos"]
accessor-dashmap = ["accessor", "opendal/services-dashmap"]
accessor-dropbox = ["accessor", "opendal/services-dropbox"]
accessor-fs = ["accessor", "opendal/services-fs"]
accessor-gcs = ["accessor", "opendal/services-gcs"]
accessor-gdrive = ["accessor", "opendal/services-gdrive"]
accessor-ghac = ["accessor", "opendal/services-ghac"]
accessor-http = ["accessor", "opendal/services-http"]
accessor-ipfs = ["accessor", "opendal/services-ipfs"]
accessor-ipmfs = ["accessor", "opendal/services-ipmfs"]
accessor-memcached = ["accessor", "opendal/services-memcached"]
accessor-memory = ["accessor", "opendal/services-memory"]
accessor-mini-moka = ["accessor", "opendal/services-mini-moka"]
accessor-moka = ["accessor", "opendal/services-moka"]
accessor-mysql = ["accessor", "opendal/services-mysql"]
accessor-obs = ["accessor", "opendal/services-obs"]
accessor-onedrive = ["accessor", "opendal/services-onedrive"]
accessor-oss = ["accessor", "opendal/services-oss"]
accessor-persy = ["accessor", "opendal/services-persy"]
accessor-postgresql = ["accessor", "opendal/services-postgresql"]
accessor-redb = ["accessor", "opendal/services-redb"]
accessor-redis = ["accessor", "opendal/services-redis"]
accessor-s3 = ["accessor", "opendal/services-s3"]
accessor-sled = ["accessor", "opendal/services-sled"]
accessor-webdav = ["accessor", "opendal/services-webdav"]
accessor-webhdfs = ["accessor", "opendal/services-webhdfs"]
all-accessors = [
    "accessor",
    "accessor-azblob",
    "accessor-azdls",
    "accessor-cacache",
    "accessor-cos",
    "accessor-dashmap",
    "accessor-dropbox",
    "accessor-fs",
    "accessor-gcs",
    "accessor-gdrive",
    "accessor-ghac",
    "accessor-http",
    "accessor-ipfs",
    "accessor-ipmfs",
    "accessor-memcached",
    "accessor-memory",
    "accessor-mini-moka",
    "accessor-moka",
    "accessor-mysql",
    "accessor-obs",
    "accessor-onedrive",
    "accessor-oss",
    "accessor-persy",
    "accessor-postgresql",
    "accessor-redb",
    "accessor-redis",
    "accessor-s3",
    "accessor-sled",
    "accessor-webdav",
    "accessor-webhdfs",
]
http-client = ["dep:reqwest", "zino-core/http-client"]
metrics = ["opendal?/layers-metrics", "zino-core/metrics"]

[dependencies]
md-5 = "0.10.6"
bytes = { workspace = true }
etag = { workspace = true }
mime_guess = { workspace = true }
multer = { workspace = true }
reqwest = { workspace = true, optional = true }
toml = { workspace = true }
tracing = { workspace = true }
zino-core = { workspace = true, features = ["http-client"] }

[dependencies.opendal]
version = "0.53.3"
optional = true
default-features = false
features = ["layers-tracing"]

[lints]
workspace = true
