# --env=dev

name = "data-cube"
version = "0.6.4"

[dirs]
uploads = "local/uploads"

[debug]
host = "127.0.0.1"
port = 6070

[main]
host = "127.0.0.1"
port = 6080

[[standby]]
host = "127.0.0.1"
port = 6081
tag = "portal"

[[standby]]
host = "127.0.0.1"
port = 6082
tag = "admin"

[database]
namespace = "dc"
max-rows = 10000

[[mariadb]]
host = "127.0.0.1"
port = 4306
database = "data_cube"
username = "root"
password = "z1lkhuvcU+c1wU/uI0MddjdtEmrj4dFxHjO+g6r5SOU"

[[mysql]]
host = "127.0.0.1"
port = 3306
database = "data_cube"
username = "root"
password = "foLLZ8gakQdmCFeMLr+jHD9MEKZ+ebLDxknFmmceZxk"

[[sqlite]]
database = "local/data/main.db"

[tracing]
filter = "info,sqlx=info,zino=trace,zino_core=trace"

[metrics]
exporter = "prometheus"
host = "127.0.0.1"
port = 9000

[jwt]
max-age = "1h"
refresh-interval = "7d"

[openapi]
custom-html = "local/docs/rapidoc.html"
