[package]
name = "amis-app"
description = "An example for amis UI generator."
version = "0.4.0"
rust-version = "1.80"
edition = "2021"
publish = false

[dependencies.phf]
version = "0.11.2"
features = ["macros"]

[dependencies.zino-amis]
path = "../../crates/zino-amis"
version = "0.3.2"

[dependencies.zino-core]
path = "../../crates/zino-core"
version = "0.31.2"
