[package]
name = "actix-app"
description = "An example for actix-web integration."
version = "0.12.1"
rust-version = "1.80"
edition = "2021"
publish = false

[dependencies]
tracing = "0.1.41"

[dependencies.actix-web]
version = "4.9.0"
default-features = false

[dependencies.serde]
version = "1.0.217"
features = ["derive"]

[dependencies.zino]
path = "../../crates/zino"
version = "0.31.1"
features = [
    "actix",
    "cookie",
    "i18n",
    "jwt",
    "opa",
    "orm",
    "view",
]

[dependencies.zino-core]
path = "../../crates/zino-core"
version = "0.31.1"
features = ["env-filter"]

[dependencies.zino-derive]
path = "../../crates/zino-derive"
version = "0.29.1"

[dependencies.zino-model]
path = "../../crates/zino-model"
version = "0.29.1"

[dependencies.zino-orm]
path = "../../crates/zino-orm"
version = "0.3.1"
features = ["orm-postgres"]
