name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Install 1.80
      run: rustup install 1.80
    - name: Set default toolchain
      run: rustup default 1.80
    - name: Install libgtk
      run: sudo apt-get install libwebkit2gtk-4.1-dev libgtk-3-dev
    - name: Build
      run: cargo build --features axum,full --verbose
    - name: Run tests
      run: cargo test --verbose
