name: Rust

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5
      - name: Install 1.85
        uses: dtolnay/rust-toolchain@v1
        with:
          toolchain: 1.85
      - name: Set default toolchain
        run: rustup default 1.85
      - name: Update packages
        run: sudo apt-get update
      - name: Install libgtk
        run: sudo apt install libwebkit2gtk-4.1-dev libgtk-3-dev libayatana-appindicator3-dev libxdo-dev
      - name: Build
        run: cargo build --features axum,full --verbose
      - name: Run tests
        run: cargo test --verbose
  doc:
      name: Documentation
      runs-on: ubuntu-latest
      env:
        RUSTDOCFLAGS: -Dwarnings

      steps:
        - uses: actions/checkout@v5
        - uses: dtolnay/rust-toolchain@nightly
        - uses: dtolnay/install@cargo-docs-rs
        - run: cargo docs-rs -p zino